import {describe,it,expect} from 'vitest';
import {data,sectors} from '../src/data';
import {analyze,references,stageFor,hasCycle,quantile} from '../src/engines/analyze';
import {emptyWorkspace,makeBrief,mergeWorkspace,validateWorkspace} from '../src/storage';
import type {Project,Workspace} from '../src/types';
const get=(name:string)=>structuredClone(data.projects.find(p=>p.id===data.fixtures[name])!);
const evaluate=(p:Project,t='2026-08-31')=>analyze(p,t);
describe('National seed integrity',()=>{
 it('has exact national, lifecycle and sector counts',()=>{expect(data.projects).toHaveLength(720);expect(data.jurisdictions).toHaveLength(36);expect(data.communities).toHaveLength(360);for(const j of data.jurisdictions){const ps=data.projects.filter(p=>p.jurisdictionId===j.id);expect(ps).toHaveLength(20);expect(ps.filter(p=>p.life==='Completed')).toHaveLength(10);expect(ps.filter(p=>p.life==='Executing')).toHaveLength(8);expect(ps.filter(p=>p.life==='Proposed')).toHaveLength(2)}for(const s of sectors)expect(data.projects.filter(p=>p.sector===s&&p.life==='Completed')).toHaveLength(45)});
 it('has unique IDs, valid links, costs and outcomes',()=>{expect(new Set(data.projects.map(p=>p.id)).size).toBe(720);for(const p of data.projects){expect(p.milestones).toHaveLength(6);for(const b of p.baselines){expect(b.cost).toBeGreaterThan(0);expect(b.finish>b.start).toBe(true)}for(const l of p.links)expect(data.communities.some(c=>c.id===l.communityId)).toBe(true);if(p.outcome){expect(p.outcome.available<'2026-07-01').toBe(true);expect(p.landmarks).toHaveLength(5);for(const l of p.landmarks)expect(l.date<p.outcome.finish).toBe(true)}}});
 it('evaluates every project at both review dates without nonfinite outputs',()=>{for(const t of ['2026-07-31','2026-08-31'])for(const p of data.projects){const a=evaluate(p,t);for(const s of a.scenarios){expect(Number.isFinite(s.delay)).toBe(true);expect(s.delay).toBeGreaterThanOrEqual(0);expect(s.finish>=t).toBe(true)}if(a.scenarios.length){expect(a.scenarios[0].delay<=a.scenarios[1].delay&&a.scenarios[1].delay<=a.scenarios[2].delay).toBe(true);expect(a.scenarios[0].exposure!<=a.scenarios[2].exposure!).toBe(true)}}});
});
describe('Date-safe and explainable analysis',()=>{
 it('distinguishes named healthy, stable late, deteriorating, stranded and missing cases',()=>{expect(evaluate(get('healthy')).status).toBe('On Track');expect(evaluate(get('delayed')).status).toBe('Delayed');expect(evaluate(get('deteriorating')).status).toBe('Deteriorating');expect(evaluate(get('stranded')).status).toBe('Stranded');expect(evaluate(get('missing')).status).toBe('Unassessed')});
 it('suppresses missing and 100% unconfirmed progress',()=>{for(const v of [null,100]){const p=get('healthy');p.reports.at(-1)!.progress=v;const a=evaluate(p);expect(a.scenarios).toHaveLength(0);expect(a.status).toBe('Unassessed');expect(a.crossEarly).toBe(null)}});
 it('does not use August values or resolutions in July',()=>{const p=get('deteriorating'),before=evaluate(p,'2026-07-31');p.reports.at(-1)!.progress=99;p.reports.at(-1)!.estimate=0;p.blockers[0].events.push({date:'2026-08-01',available:'2026-08-01',status:'closed'});const after=evaluate(p,'2026-07-31');expect(after.scenarios).toEqual(before.scenarios);expect(after.status).toBe(before.status);expect(after.blockers.map(x=>x.blocker.id)).toEqual(before.blockers.map(x=>x.blocker.id));expect(after.rows).toEqual(before.rows)});
 it('suppresses negative progress corrections without historical fallback',()=>{const p=get('healthy');p.reports.at(-1)!.progress=1;const a=evaluate(p);expect(a.scenarios).toHaveLength(0);expect(a.status).toBe('Unassessed')});
 it('uses historical scenarios for near-zero progress, not decades of linear projection',()=>{const a=evaluate(get('stranded'));expect(a.method).toContain('Historical');expect(a.scenarios[1].months).toBeLessThan(240)});
 it('preserves original-baseline delay after a revision',()=>{const a=evaluate(get('revision'));expect(a.originalDelay).toBeGreaterThan(a.reportedDelay!);expect(a.limitations.some(x=>x.includes('Baseline changed'))).toBe(true)});
 it('rejects an unavailable baseline rather than leaking its future values',()=>{const p=get('healthy');p.baselines[0].available='2026-09-01';expect(()=>evaluate(p)).toThrow('baseline')});
 it('keeps reference sector, stage and minimum count',()=>{const p=get('healthy'),stage=stageFor(p.reports.at(-1)!.progress),r=references(p,'2026-08-31',stage);expect(r.refs.length).toBeGreaterThanOrEqual(5);for(const x of r.refs)expect(data.projects.find(p=>p.id===x.id)!.sector).toBe(p.sector);const sparse={...data,projects:data.projects.filter(x=>r.refs.slice(0,4).some(y=>y.id===x.id))};expect(references(p,'2026-08-31',stage,sparse).refs).toHaveLength(0)});
 it('does not return cost exposure from inconsistent reported costs',()=>{const p=get('healthy');p.reports.at(-1)!.estimate=0;const a=evaluate(p);expect(a.scenarios.every(s=>s.exposure===null)).toBe(true);expect(a.feasibility.checks[2].state).toBe('Unknown')});
 it('separates existing exposure from additional exposure',()=>{const a=evaluate(get('deteriorating'));for(const s of a.scenarios){expect(s.finalCost).toBeCloseTo(a.report!.estimate!+s.extraCost!);expect(s.exposure).toBeCloseTo(Math.max(0,s.finalCost!-a.baseline.cost))}});
 it('recognizes already-breached threshold and negative slack',()=>{const a=evaluate(get('deteriorating'));expect(a.crossEarly).toBe(0);expect(a.queue).toBe('Immediate review');expect(a.slack).toBeLessThan(0)});
 it('does not restart an expired blocker lead time',()=>{const p=get('deteriorating');p.blockers[0].estimateDate='2026-01-01';const a=evaluate(p);expect(a.blockers[0].max).toBeNull();expect(a.slack).toBeNull();expect(a.queue).toBe('Immediate review')});
 it('deduplicates beneficiaries and future commitments are target-date bounded',()=>{const p=get('healthy');const a=evaluate(p);p.links.push({...p.links[0]});expect(evaluate(p).population).toBe(a.population);p.reports.at(-1)!.released=0;p.reports.at(-1)!.commitments.forEach(c=>c.due='2099-01-01');expect(evaluate(p).feasibility.checks[2].state).toBe('Fail')});
 it('handles unknown recovery target and missing funding evidence',()=>{const a=analyze(get('healthy'),'2026-08-31','2026-08-01');expect(a.feasibility.label).toBe('Needs target date')});
 it('detects cycles without flagging shared prerequisites',()=>{expect(hasCycle([{from:'A',to:'B'},{from:'A',to:'C'},{from:'C',to:'B'}])).toBe(false);expect(hasCycle([{from:'A',to:'B'},{from:'B',to:'A'}])).toBe(true)});
 it('uses interpolated quantiles',()=>{expect(quantile([40,10,30,20],.25)).toBe(17.5);expect(quantile([], .5)).toBeNull()});
});
describe('Officer backup integrity',()=>{
 const base=()=>{const w=emptyWorkspace();const b=makeBrief(evaluate(get('healthy')),'Test');w.briefs.push(b);w.decisions.push({id:'d1',briefId:b.id,action:'Monitor',owner:'QA officer',due:'2026-10-01',rationale:'Synthetic QA',created:'2026-09-30T10:00:00Z'});w.followups.push({id:'f1',decisionId:'d1',note:'Test follow-up',observed:'2026-09-30',created:'2026-09-30T10:00:00Z'});return w};
 it('allows a standalone brief and round trips valid JSON',()=>{const w=base();expect(validateWorkspace(JSON.parse(JSON.stringify(w)))).toEqual(w);expect(validateWorkspace({...w,decisions:[],followups:[]})).toBeTruthy()});
 it('rejects dangling records, duplicate IDs and malformed dates',()=>{const w=base();expect(()=>validateWorkspace({...w,briefs:[]})).toThrow();expect(()=>validateWorkspace({...w,briefs:[...w.briefs,...w.briefs]})).toThrow();w.decisions[0].due='2026-02-31';expect(()=>validateWorkspace(w)).toThrow()});
 it('restoring an identical backup never duplicates records',()=>{const w=base();expect(mergeWorkspace(w,structuredClone(w),true)).toEqual(w)});
 it('copies conflicting parents and remaps otherwise identical children',()=>{const w=base(),incoming=structuredClone(w);incoming.briefs[0].snapshot.change='Different';const merged=mergeWorkspace(w,incoming,true);expect(merged.briefs).toHaveLength(2);expect(merged.decisions).toHaveLength(2);expect(merged.followups).toHaveLength(2);expect(merged.decisions[1].briefId).toBe(merged.briefs[1].id);expect(merged.followups[1].decisionId).toBe(merged.decisions[1].id);expect(merged.briefs[0]).toEqual(w.briefs[0])});
 it('skipping conflicts leaves original history intact',()=>{const w=base(),incoming=structuredClone(w);incoming.briefs[0].snapshot.change='Different';expect(mergeWorkspace(w,incoming,false)).toEqual(w)});
 it('rejects unexpected versions and invalid notes',()=>{expect(()=>validateWorkspace({version:2})).toThrow();const w=base();w.followups[0].note=' ';expect(()=>validateWorkspace(w)).toThrow()});
});
