import {Check,Clock,TrendingDown,PauseCircle,HelpCircle,Layers,FolderKanban,CalendarDays} from 'lucide-react';
import {data} from './data';
import type {Project} from './types';
import {useState} from 'react';
export const jurisdiction=(p:Project)=>data.jurisdictions.find(j=>j.id===p.jurisdictionId)!.name;
export function Badge({status}:{status:string}){const Icon=status==='On Track'||status==='Completed'?Check:status==='Delayed'?Clock:status==='Deteriorating'?TrendingDown:status==='Stranded'?PauseCircle:HelpCircle;return <span className={`badge status-${status.toLowerCase().replaceAll(' ','-')}`}><Icon size={13}/>{status}</span>}
export function Metric({label,value,detail,icon:Icon=Layers}:{label:string;value:string;detail:string;icon?:typeof Layers}){return <article className="metric"><div className="metric-label">{label}<Icon size={18}/></div><strong>{value}</strong><span>{detail}</span></article>}
export function Empty({title,detail}:{title:string;detail?:string}){return <div className="empty"><FolderKanban size={29}/><h3>{title}</h3>{detail&&<p>{detail}</p>}</div>}
export function DateSelect({cutoff,setCutoff}:{cutoff:string;setCutoff:(v:string)=>void}){return <label className="date-select"><CalendarDays size={16}/><select aria-label="Review date" value={cutoff} onChange={e=>setCutoff(e.target.value)}><option value="2026-08-31">31 August 2026</option><option value="2026-07-31">31 July 2026</option></select></label>}
export function NationMap({projects,onPick,selected}:{projects:Project[];onPick:(s:string)=>void;selected:string}){const [hover,setHover]=useState('');return <div className="nation-map"><svg viewBox="0 0 550 340" role="img" aria-label="Jurisdiction locations across India; reference coordinates, not political boundaries"><defs><pattern id="grid" width="25" height="25" patternUnits="userSpaceOnUse"><circle cx="1" cy="1" r=".65" fill="#cbdfe4"/></pattern></defs><rect width="550" height="340" fill="url(#grid)"/>{[10,20,30].map(lat=><text key={lat} x="14" y={326-(lat-8)*10} fill="#617e88" fontSize="10">{lat}°N</text>)}{data.jurisdictions.map(j=>{const count=projects.filter(p=>p.jurisdictionId===j.id).length;if(!count)return null;const x=85+(j.lon-68)*12,y=326-(j.lat-8)*10;return <g key={j.id} className="map-point" tabIndex={0} role="button" aria-label={`${j.name}, ${count} projects`} onClick={()=>onPick(selected===j.id?'':j.id)} onKeyDown={e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();onPick(selected===j.id?'':j.id)}}} onMouseEnter={()=>setHover(j.name)} onMouseLeave={()=>setHover('')} onFocus={()=>setHover(j.name)} onBlur={()=>setHover('')}><circle cx={x} cy={y} r={selected===j.id?12:8} fill="#86CED9" opacity=".4"/><circle cx={x} cy={y} r={selected===j.id?6:4} fill="#187C94" stroke="white" strokeWidth="1.6"/><title>{j.name}: {count} projects</title></g>})}<text x="335" y="294" fontSize="11" fill="#426b79">BAY OF BENGAL</text><text x="65" y="256" fontSize="11" fill="#426b79">ARABIAN SEA</text></svg><div className="map-caption"><span><span className="legend-dot"/> {hover||'Select a location to explore'}</span><span>Reference locations · not boundaries</span></div></div>}
